spring.application.name=RLibraryBackend
cors.allowed-origins=http://localhost:4200
spring.datasource.url=jdbc:h2:mem:rlibrary;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.hibernate.ddl-auto=create-drop
spring.h2.console.enabled=true
spring.jpa.show-sql=false
spring.sql.init.mode=always
spring.jpa.defer-datasource-initialization=true
spring.datasource.name=test
logging.level.com.example.rlibrarybackend.controller=INFO
logging.level.com.example.rlibrarybackend.service=INFO
swagger.ui.auto-open=true

spring.security.oauth2.resourceserver.jwt.issuer-uri=https://dev-m362yc372ygvz1ny.us.auth0.com/
spring.security.oauth2.resourceserver.jwt.audiences=https://rlibrary.com

okta.oauth2.issuer=https://dev-m362yc372ygvz1ny.us.auth0.com/
okta.oauth2.audience=https://rlibrary.com
okta.oauth2.client-id=PWhKXAtNqwZuxF1njrQ55ulHNS1aYIr5


#eigen documentatie gebruiken ipv swagger generatie
springdoc.api-docs.enabled=true
springdoc.swagger-ui.url=/openapi.yml
springdoc.swagger-ui.oauth.client-id=${okta.oauth2.client-id}
springdoc.swagger-ui.persistAuthorization=true
springdoc.swagger-ui.oauth.app-name=RLibraryBackend