spring.application.name=RLibraryBackend

# -Dspring.profiles.active=postgres for production.
spring.profiles.active=dev

spring.security.oauth2.resourceserver.jwt.issuer-uri=https://dev-m362yc372ygvz1ny.us.auth0.com/
spring.security.oauth2.resourceserver.jwt.audiences=https://rlibrary.com

okta.oauth2.issuer=https://dev-m362yc372ygvz1ny.us.auth0.com/
okta.oauth2.audience=https://rlibrary.com
okta.oauth2.client-id=PWhKXAtNqwZuxF1njrQ55ulHNS1aYIr5

swagger.ui.auto-open=true
springdoc.api-docs.enabled=true
springdoc.swagger-ui.url=/openapi.yml
springdoc.swagger-ui.oauth.client-id=${okta.oauth2.client-id}
springdoc.swagger-ui.persistAuthorization=true
springdoc.swagger-ui.oauth.app-name=RLibraryBackend